#!/usr/bin/bash
# Add a new user to the system with the usermod command
usermod -aG sudo mkellia

# Create a new entry for user 'mkellia' in /etc/passwd with the given details:
echo "mkellia:x:$(id -u mkellia):$(id -g mkellia):Mkellia:/home/mkellia:/bin/bash" >> /etc/passwd

# Create a new entry for user 'mkellia' in /etc/shadow with a placeholder password (which will need to be set upon first login):
echo "mkellia:*:$(chage -m 0 -M 99999 mkellia -d 0):17647:0:99999:7:::" >> /etc/shadow

# Verify that the new entries for user 'mkellia' are in the files:
grep mkellia /etc/passwd /etc/shadow
